version: "3.7"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "postgres:/var/lib/postgresql/data"
  web:
    depends_on:
      - "pgadmin"
    build:
      context: .
      args:
        WWWGROUP: "${WWWGROUP}"
    command: bash -c "bundle exec rake spec"
    volumes:
      - "bundle_cache:/bundle"
      - ".:/app"
      - .env:/app/.env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DISABLE_SPRING: 1
volumes:
  postgres:
  bundle_cache:
