on:
  release:
    types: [published]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Update Spree On Server
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          echo "$SSH_REMOTE_HOST" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          SSH_REMOTE_HOST: ${{secrets.REMOTE_HOST}}
      - uses: actions/checkout@v3
      - name: Update Dependencies Using Bundle
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private.key $SSH_REMOTE_USER@$SSH_REMOTE_HOST "
                  cd $REMOTE_TARGET &&
                  docker compose down &&
                  docker compose run --rm web bundle update spree_avior_tax &&
                  docker compose up -d;"
        env:
          SSH_REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
